-- Таблицы
create table assignment (
	id bigint generated by default as identity,
	title varchar(255) not null,
	primary key (id)
);
create table designer (
	id bigint generated by default as identity,
	name varchar(255) not null,
	primary key (id)
);
create table engine (
	id bigint generated by default as identity,
	engine_type varchar(255) not null,
	primary key (id)
);
create table airplane (
	id bigint generated by default as identity,
	title varchar(255),
	brand varchar(255) not null,
	engine_id bigint not null,
	assignment_id bigint not null,
	designer_id bigint not null,
	primary key (id)
);

-- Уникальность
alter table airplane add constraint UK_j6lofxb1aa067s1iw3qav5n39 unique (brand);
alter table assignment add constraint UK_3vaohoyn79gauvrkn0clcw8ux unique (title);
alter table designer add constraint UK_2ve1r3nu8jw1xk43vkuxbx22d unique (name);
alter table engine add constraint UK_elmbkc59dlxm2iumtu8nai3q4 unique (engine_type);

-- Отношения
alter table airplane add constraint FK7sn3lcqni329xt2jknodbss9 foreign key (engine_id) references engine;
alter table airplane add constraint FK5w2o8sklp7dn2rh1ixoxvv6bh foreign key (assignment_id) references assignment;
alter table airplane add constraint FKex2ckv8uow8bnmdm3ei6ow7ju foreign key (designer_id) references designer;
